server:
  tomcat:
    uri-encoding: UTF-8
    #最大链接数
    max-connections: 100000
    #最大等待队列长度
    accept-count: 1000
    #请求头最大长度kb
    max-http-header-size: 1048576
    #请求个数超过这个数，强制关闭掉socket链接
    max-kepp-alive-requests: 300
    #下次请求过来之前，socket链接保持多久
    keep-alive-time-out: 60000
    #请请求体最大长度kb
    #max-http-post-size: 2097152
    connection-timeout: 12000
    threads:
      min-spare: 500
      max: 2500
  #服务http端口
  port: 9191
  servlet:
    #访问根路径
    context-path: /

management:
  info:
    os:
      enabled: true

spring:
  application:
    name: spring-boot-api
  profiles:
    active: native
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mltt.model
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl